### ISSUE TITLE
dashes in role names are not allowed by ansible

### ISSUE THREAD

**Issue by reduzent** [Graylog2/graylog-ansible-role#178]
According to https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names `-`-characters should not be used in ansible roles.  I understand that it was common to prefix role names with `andible-role-` in Galaxy. Thus, the documentation suggests to add an extra field to `meta/main.yml`:

```
galaxy_info:
  role_name: graylog
```

**Comment by juju2112** [comment]
Leaving this open until I get time to release it and make sure it's right.

**Comment by juju2112** [comment]
I hate that the old url (https://galaxy.ansible.com/Graylog2/graylog-ansible-role) is now a dead link. Not even a redirect! This will break anyone trying to pull the role using the old name. 

BUT, I upgraded Ansible on my machine yesterday and it was giving me errors because of the dashes in the name. Applying this fix was the only thing that would let me run it. 

It seems like the naming standards changed out from under us over the years. I hate breaking changes, but hopefully this is defensible.

**Comment by dragona-Ocient** [comment]
We don't use the galaxy role, this was our own role.
