### ISSUE TITLE
Branch rename in upstream elasticsearch

### ISSUE THREAD

**Issue by kbcz1989** [Graylog2/graylog-ansible-role#182]
Hello,

ansible-galaxy fails to install requirements because of an upstream branch rename [#828](https://github.com/elastic/ansible-elasticsearch/pull/828).

**Comment by malcyon** [comment]
I thought I fixed that. It should be good in our `main` branch. 

https://github.com/Graylog2/graylog-ansible-role/commit/24513cb0cc808db6f563a96bf9de7c66dc705301

I may need to update the reference in `meta/main.yml`, too. 

I'll look into it and see about pushing a new version to Ansible Galaxy.

**Comment by malcyon** [comment]
@kbcz1989 Okay. it seems to be fixed now. I can install it successfully in a fresh VM:

```
vagrant@instance:~$ ansible-galaxy install graylog2.graylog
- downloading role 'graylog', owned by graylog2
- downloading role from https://github.com/Graylog2/graylog-ansible-role/archive/3.3.7.tar.gz
- extracting graylog2.graylog to /home/vagrant/.ansible/roles/graylog2.graylog
- graylog2.graylog (3.3.7) was installed successfully
- adding dependency: lean_delivery.java (7.1.0)
- adding dependency: elastic.elasticsearch (main)
- downloading role 'java', owned by lean_delivery
- downloading role from https://github.com/lean-delivery/ansible-role-java/archive/7.1.0.tar.gz
- extracting lean_delivery.java to /home/vagrant/.ansible/roles/lean_delivery.java
- lean_delivery.java (7.1.0) was installed successfully
- extracting elastic.elasticsearch to /home/vagrant/.ansible/roles/elastic.elasticsearch
- elastic.elasticsearch (main) was installed successfully
```

Thanks for letting me know!

I will try to set up a CI soon that will test the install. 

Unfortunately, I had to revert this repo's branch from `main` back to `master`, because Ansible Galaxy refused to use it and would only pull the deleted `master` branch. Ugh! I wonder if Elasticsearch is having the same issue. 

In any case, it seems to be working now!
