### ISSUE TITLE
Version 2.3.0: Breaking Change Somewhere

### ISSUE THREAD

**Issue by fxfitz** [Graylog2/graylog-ansible-role#77]
@mariussturm With the latest release of 2.3.0, it seems as if the update has broken production system. Still debugging as to what exactly happened, but I wanted to let you know about what appears to be a breaking change with the latest release.

**Comment by mariussturm** [comment]
@fxfitz 2.3 is not a drop-in upgrade. Please read the upgrade notes to debug what went wrong: https://github.com/Graylog2/graylog2-server/blob/2.3/UPGRADING.rst
On the Graylog side we changed to the ES http protocol, this needs to be configured and accessable. On the Ansible side we did a bigger refactoring of this role. Updated Elasticsearch to 5.x, rerplaced the MongoDB role with custome code and changed configuration templates. So not ideal for unattended upgrades.

**Comment by fxfitz** [comment]
Ah, you're totally right! Sorry, I had not seen that document and our CI is set up to automatically pull the latest role version from Galaxy.

Before closing this issue, do you know if the Ansible role versions will do clean upgrades from 2.2.3 to 2.3.0?

**Comment by mariussturm** [comment]
There is no special migration code in the role. It will just write an updated server.conf file and tries to install the latest Graylog server package. So it's up to you to update Elasticsearch to 5.x and set `elasticsearch_hosts` accodingly.
Additionally you have to remove the 2.2 repository package before applying this role. Otherwise it will fail to install the latest server.

**Comment by fxfitz** [comment]
Great, thanks for the info, @mariussturm! :-D
